name: CI/CD - Angular + Spring Boot to EC2 (Windows)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Angular App
      working-directory: frontEnd-demo/demoFrontend
      run: |
        npm install
        npm run build --prod

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Spring Boot App
      working-directory: demo/demo
      run: ./mvnw clean package -DskipTests

             
    - name: Upload Angular frontend
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "frontEnd-demo/demoFrontend/dist/demo-frontend/*"
        target: "C:/application/FE/"

    - name: Upload Spring Boot jar
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "demo/demo/target/demo-0.0.1-SNAPSHOT.jar"
        target: "C:/application/"


    - name: Stop Spring Boot Windows Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          powershell -Command "Stop-Service -Name 'AkanitaSpringBootService'"

          
    - name: Replace old app and restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cmd /c "(cd C:/application ) & (move /Y C:\application\FE\frontEnd-demo\demoFrontend\dist\demo-frontend\* C:\application\FE\demo-frontend\ || echo MOVE FAILED) & (move /Y C:\application\demo\demo\target\demo-0.0.1-SNAPSHOT.jar C:\application\ || echo MOVE FAILED) & (cd C:\application\nginx-1.28.0) & (nginx.exe -s reload)"
          

    - name: Restart Spring Boot Windows Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          powershell -Command "Restart-Service -Name 'AkanitaSpringBootService'"
        
    
