name: CI/CD - Angular + Spring Boot to EC2 (Windows)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Angular App
      working-directory: frontEnd-demo/demoFrontend
      run: |
        npm install
        npm run build --prod

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Spring Boot App
      working-directory: demo/demo
      run: ./mvnw clean package -DskipTests

    - name: Deploy to EC2 via WinRM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        # password: ${{ secrets.EC2_PASSWORD }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        command: |
          mkdir C:\application\frontend_new
          mkdir C:\application\backend_new

    - name: Upload Angular frontend
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        # password: ${{ secrets.EC2_PASSWORD }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "frontEnd-demo/demoFrontend/dist/demo-frontend/**"
        target: "C:/application/FE/"

    - name: Upload Spring Boot jar
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        # password: ${{ secrets.EC2_PASSWORD }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "demo/demo/target/demo-0.0.1-SNAPSHOT.jar"
        target: "C:/application/"

    - name: Replace old app and restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        # password: ${{ secrets.EC2_PASSWORD }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        command: |
          # taskkill /F /IM java.exe
          # timeout /t 3
          # REM Move frontend build files to FE/demo-frontend
          # if not exist C:\application\FE\demo-frontend mkdir C:\application\FE\demo-frontend
          # for %f in (C:\application\FE\frontEnd-demo\demoFrontend\dist\demo-frontend\*) do move /Y "%f" C:\application\FE\demo-frontend\
          # REM Move backend jar (if needed)
          # move /Y C:\application\demo\demo\target\demo-0.0.1-SNAPSHOT.jar C:\application\
          # REM Start Spring Boot app
          # start /B java -jar C:\application\demo-0.0.1-SNAPSHOT.jar
          # REM Reload Nginx
          # cd C:\application\nginx-1.28.0
          # nginx.exe -s reload

                  
          taskkill /F /IM java.exe
          timeout /t 3
          # move C:\application\backend_new\demo-0.0.1-SNAPSHOT.jar C:/application/FE/demo-frontend
          # move /Y C:\application\backend_new\demo-0.0.1-SNAPSHOT.jar C:/application\
          move /Y C:/application/FE/frontEnd-demo/demoFrontend/dist/demo-frontend/** C:/application/FE/demo-frontend
          move /Y C:/application/demo/demo/target/demo-0.0.1-SNAPSHOT.jar C:/application/
          start /B java -jar C:\application\demo-0.0.1-SNAPSHOT.jar  
          cd C:\application\nginx-1.28.0
          # nginx.exe -s reload
          start /B nginx
